### ISSUE TITLE
"Not a JSON Object" when people join the server.

### ISSUE THREAD

**Issue by FPSUsername** [StylexTV/UltimateHeads#4]
When players join my server, I get this error. Running the latest Paper 1.16.4 server using Java 15 JDK.

I believe that this is due to the server running in offline mode, it would be nice if this bug could be solved.

```
[19:33:58] [Server thread/ERROR]: Could not pass event PlayerLoginEvent to UltimateHeads v1.5
java.lang.IllegalStateException: Not a JSON Object: null
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90) ~[patched_1.16.4.jar:git-Paper-312]
	at de.stylextv.ultimateheads.util.ItemUtil.getPlayerUUID(ItemUtil.java:284) ~[?:?]
	at de.stylextv.ultimateheads.util.ItemUtil.getHeadValue(ItemUtil.java:274) ~[?:?]
	at de.stylextv.ultimateheads.head.HeadManager.addPlayerToLocalHeads(HeadManager.java:244) ~[?:?]
	at de.stylextv.ultimateheads.event.EventPlayerJoinQuit.onPlayerLogin(EventPlayerJoinQuit.java:17) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor64.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-312]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-312]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-312]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.PlayerList.attemptLogin(PlayerList.java:667) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.LoginListener.c(LoginListener.java:148) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.LoginListener.tick(LoginListener.java:66) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:383) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:145) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1381) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-312]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by stylextv** [comment]
Should be fixed now
