### ISSUE TITLE
JSON Null error on startup

### ISSUE THREAD

**Issue by FPSUsername** [StylexTV/UltimateHeads#6]
A new bug when starting up the server.
I assume this is because Paper has been updated.

java version "15.0.1" 2020-10-20
Paper 1.16.4 build 346 (27th of December)
UltimateHeads version 1.8 (also tested it with 1.7)

```
[14:04:42] [Server thread/ERROR]: Error occurred while enabling UltimateHeads v1.8 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.json.simple.JSONArray.iterator()" because "json" is null
	at de.stylextv.ultimateheads.head.HeadManager.loadHeads(HeadManager.java:63) ~[?:?]
	at de.stylextv.ultimateheads.head.HeadManager.loadHeads(HeadManager.java:45) ~[?:?]
	at de.stylextv.ultimateheads.main.Main.onEnable(Main.java:41) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:git-Paper-346]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[server.jar:git-Paper-346]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[server.jar:git-Paper-346]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[server.jar:git-Paper-346]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[server.jar:git-Paper-346]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:469) ~[server.jar:git-Paper-346]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[server.jar:git-Paper-346]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[server.jar:git-Paper-346]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[server.jar:git-Paper-346]
	at java.lang.Thread.run(Thread.java:832) [?:?]
[14:04:42] [Server thread/INFO]: [UltimateHeads] Disabling UltimateHeads v1.8
[14:04:42] [Server thread/ERROR]: Error occurred while disabling UltimateHeads v1.8 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "de.stylextv.ultimateheads.service.AutoUpdater.startAutoUpdater()" because "this.autoUpdater" is null
	at de.stylextv.ultimateheads.main.Main.onDisable(Main.java:86) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[server.jar:git-Paper-346]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[server.jar:git-Paper-346]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[server.jar:git-Paper-346]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[server.jar:git-Paper-346]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[server.jar:git-Paper-346]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[server.jar:git-Paper-346]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[server.jar:git-Paper-346]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:469) ~[server.jar:git-Paper-346]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[server.jar:git-Paper-346]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[server.jar:git-Paper-346]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[server.jar:git-Paper-346]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by stylextv** [comment]
Hey, the the database of heads was offline yesterday. Can you check if this still happens?

**Comment by FPSUsername** [comment]
Seems like the problem is still there for me. Perhaps you could share the exact domain of the database, it could be that my DNS is blocking the domain (although I'm not seeing anything odd in the logs)

**Comment by stylextv** [comment]
Could you, if you see this file, delete heads.json inside plugins/UltimateHeads and try again?

**Comment by FPSUsername** [comment]
Yes, that fixed the issue. heads.json and data.json were empty. I deleted both and it works fine now
